### ISSUE TITLE
the canvas render video twice vertically 

### ISSUE THREAD

**Issue by iamike** [gka/canvid#14]
please check the screen shot?
![2015-12-31 10 07 01](https://cloud.githubusercontent.com/assets/526854/12065016/f6e499fc-b00a-11e5-9abc-b38654fe194c.png)

**Comment by moklick** [comment]
Are the numbers of the frames and cols params correct?

**Comment by iamike** [comment]
Sorry,just check the example. Framerate didn't set. Fixed.thanks
