### ISSUE TITLE
Suggest alternative for full-video playback

### ISSUE THREAD

**Issue by fregante** [gka/canvid#19]
Hello, I'm unsure of how to ask this in a non-awkward way, but would it make sense to suggest [iphone-inline-video](https://github.com/bfred-it/iphone-inline-video) in the _readme_ as an alternative solution that overcomes the two limitations of canvid? (i.e. short+soundless)

**Comment by gka** [comment]
done

**Comment by fregante** [comment]
Awesome! 👍
