### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Shuunen** [gka/canvid#2]
Hi there :)

I see you on http://tympanus.net/codrops/collective/collective-180/,

Your lib seems nice, a small example of it's usage will be cool, on CodePen or similar websites,

What do you think ?

**Comment by moklick** [comment]
Sure thing! We will add an example in the next days!

**Comment by moklick** [comment]
@Shuunen you can now find a demo here http://gka.github.io/canvid/

**Comment by Shuunen** [comment]
nice ! thanks :)
