### ISSUE TITLE
Is there a way to load clip on demand for saving web flow data?

### ISSUE THREAD

**Issue by zheeeng** [gka/canvid#21]
The video clips like: 

```
{
  clip00: {src: 'static/video/00.jpg', frames: 24, cols: 6, fps: 12},
  clip01: {src: 'static/video/01.jpg', frames: 24, cols: 6, fps: 12},
  clip02: {src: 'static/video/02.jpg', frames: 24, cols: 6, fps: 12},
  clip04: {src: 'static/video/04.jpg', frames: 24, cols: 6, fps: 12},
  clip05: {src: 'static/video/05.jpg', frames: 24, cols: 6, fps: 12},
}
```

I visit the website and the canvid will switch the clip to a specific one in some condition.  Is there a way for saving the transferred network data if some clips have no necessary being played?
Or I have to get the condition first then create the canvid dynamically?

**Comment by moklick** [comment]
We load everything that is defined under the `videos` parameter. So if you want to load only specific ones you need create the canvid dynamically.
