### ISSUE TITLE
Pass more styles to canvid beyond width and height

### ISSUE THREAD

**Issue by michaelcjoseph** [gka/canvid#26]
I could be wrong but there doesn't seem to be a way to do this right now. As a workaround, in my own CSS, I added the .canvid class and added the extra styling that I wanted, but I'd prefer to be able to pass through the canvid creation function instead.

**Comment by gka** [comment]
I think width and height are sufficient. You are free to use CSS definitions or JS to set additional styles, using a library such as D3.js or jQuery or just vanilla JS.
