### ISSUE TITLE
Support for Dom element as a selector

### ISSUE THREAD

**Issue by tadaskarpavicius** [gka/canvid#3]
So I can do this:
var canvidControl = canvid({
    selector : document.querySelector(".myelement"),
    videos: {
        clip1: { src: 'clip1.jpg', frames: 38, cols: 6 },
        clip2: { src: 'clip2.jpg', frames: 43, cols: 6, loops: 3 }
    },
    width: 500,
    height: 400,
    loaded: function() {
        canvidControl.play('clip1');
        // reverse playback
        // canvidControl.play('clip1', true);
    }
});

I have multiple videos on page and all of them have same selectors.

**Comment by moklick** [comment]
Good idea!

**Comment by moklick** [comment]
should work now https://github.com/gka/canvid/blob/master/canvid.js#L24
