### ISSUE TITLE
Destroy method

### ISSUE THREAD

**Issue by tadaskarpavicius** [gka/canvid#4]
It would be awesome to have a destroy method.

**Comment by moklick** [comment]
With destroy, you mean removing the created canvas element from the DOM?

**Comment by tadaskarpavicius** [comment]
Yes, stopping video if it is playing and removing canvas

**Comment by moklick** [comment]
@trajektorijus we now have a destroy function https://github.com/gka/canvid/blob/master/canvid.js#L73
