### ISSUE TITLE
Broken in Chrome 46 for Android

### ISSUE THREAD

**Issue by pygy** [gka/canvid#5]
I've tried it on a Android 4.3 device with Chrome 46, and the canvas ends up larger than the frame. I don't see a video, but rather, a scrolling fly by over the sprite sheet.

**Comment by moklick** [comment]
Thanks for the hint. What is the size of your sprite in pxs?

**Comment by pygy** [comment]
​Sorry, I should have given more details. I'm talking​ about the demo of
the home page: http://gka.github.io/canvid/#demo

I can't give you the specs of the device (screen size/RAM) right now, because I
don't have the phone at hand, and I don't want to wake up its owner. I'll
give you more info tomorrow if you need it.

**Comment by moklick** [comment]
Ok. I encountered similar problems on Android+Chrome when the sprites were to large. Unfortunately I can't find any specification about the max size of an image you can handle with a canvas element. For now I will just add a warning to the readme.
