### ISSUE TITLE
Audio sync

### ISSUE THREAD

**Issue by YOzaz** [gka/canvid#8]
If you'd add a method / property which returns current frame / time, it can be extended to sync with audio in the background.

**Comment by moklick** [comment]
canvid will not sync with audios, but a getter and setter for the frames is a good idea.

**Comment by YOzaz** [comment]
Yes, I need just a getter ;) setter can be called "seekTo", e.g.
Will create sync separately (it shouldn't be difficult though).

**Comment by moklick** [comment]
I added the functions `getCurrentFrame` and `setCurrentFrame`.
