### ISSUE TITLE
Integrate a canvid within a canvas

### ISSUE THREAD

**Issue by nltesown** [gka/canvid#9]
Hi, thanks for canvid, it's a great idea. I have very little experience of canvas and I was wondering if it was possible to integrate a canvid video within the wider "context" (in the ordinary sense) of a canvas element, so the canvas could contain other stuff along with the canvid(s).

**Comment by gka** [comment]
why don't you just stack multiple canvas elements on top of each other? to me, that sounds like a cleaner solution.

**Comment by nltesown** [comment]
Yes, thanks for the suggestion.
